name = "build-tracker"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "build-tracker-db"
database_id = "b15d0abd-c82e-4a6c-8597-42dffd08e326"